[".Autohotkey/Lib/jsongo.v2.ahk"]
  type = "file"
  url = "https://raw.githubusercontent.com/GroggyOtter/jsongo_AHKv2/refs/heads/main/src/jsongo.v2.ahk"
  refreshPeriod = "168h"
[".Autohokey/Lib/peep.v2.ahk"]
  type = "file"
  url = "https://raw.githubusercontent.com/GroggyOtter/PeepAHK/refs/heads/main/script/Peep.v2.ahk"
  refreshPeriod = "168h"

